ALTER TABLE payments
    MODIFY COLUMN status ENUM('PENDING','PROCESSING','AWAITING_CONFIRMATION','COMPLETED','FAILED','REFUNDED','DISPUTED') NOT NULL DEFAULT 'PENDING';

ALTER TABLE payments
    ADD COLUMN client_confirmed_payment BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN worker_confirmed_receipt BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN client_confirmed_at DATETIME NULL,
    ADD COLUMN worker_confirmed_at DATETIME NULL;

ALTER TABLE notifications
    MODIFY COLUMN type ENUM(
        'NEW_TASK','TASK_ACCEPTED','TASK_STARTED','TASK_COMPLETED',
        'TASK_CANCELLED','NEW_MESSAGE','PAYMENT_RECEIVED',
        'PAYMENT_AWAITING_CONFIRMATION','PAYMENT_DISPUTED',
        'REVIEW_RECEIVED','ACCOUNT_VERIFIED','SYSTEM'
    ) NOT NULL;
